MAC_INSTALL=/home/james/Source/MAC_v_2_6_1
APP=Star_Nobeacon

gawk -f fileprep.awk $MAC_INSTALL/Applications/Helper_Files/SIO_Support/Src/sio_handler.c > ./sio_handler.c
gawk -f fileprep.awk $MAC_INSTALL/Resources/Buffer_Management/Src/bmm.c > ./bmm.c
gawk -f fileprep.awk $MAC_INSTALL/Resources/Queue_Management/Src/qmm.c > ./qmm.c
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Src/tal_pwr_mgmt.c > ./tal_pwr_mgmt.c
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Src/tal_init.c > ./tal_init.c
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Src/tal_pib.c > ./tal_pib.c
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Src/tal_rx.c > ./tal_rx.c
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Src/tal.c > ./tal.c
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Src/tal_rx_enable.c > ./tal_rx_enable.c
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Src/tal_tx.c > ./tal_tx.c
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Src/tal_ed.c > ./tal_ed.c
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Src/tal_slotted_csma.c > ./tal_slotted_csma.c
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Src/tal_irq_handler.c > ./tal_irq_handler.c
gawk -f fileprep.awk $MAC_INSTALL/TFA/ATMEGARF_TAL_1/Src/tfa.c > ./tfa.c
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/Generic/Src/pal_flash.c > ./pal_flash.c
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/Generic/Src/pal_utils.c > ./pal_utils.c
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/Generic/Src/pal.c > ./pal.c
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/Generic/Src/pal_uart.c > ./pal_uart.c
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/ATMEGA128RFA1/Src/pal_irq.c > ./pal_irq.c
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/ATMEGA128RFA1/Src/pal_timer.c > ./pal_timer.c
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/ATMEGA128RFA1/Src/pal_usb_ftdi.c > ./pal_usb_ftdi.c
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/ATMEGA128RFA1/Src/pal_mcu_generic.c > ./pal_mcu_generic.c
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/ATMEGA128RFA1/Src/pal_sio_hub.c > ./pal_sio_hub.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_callback_wrapper.c > ./mac_callback_wrapper.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_tx_coord_realignment_command.c > ./mac_tx_coord_realignment_command.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac.c > ./mac.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_orphan.c > ./mac_orphan.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_poll.c > ./mac_poll.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_associate.c > ./mac_associate.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_dispatcher.c > ./mac_dispatcher.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_start.c > ./mac_start.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_beacon.c > ./mac_beacon.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_sync.c > ./mac_sync.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_data_ind.c > ./mac_data_ind.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_process_beacon_frame.c > ./mac_process_beacon_frame.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_rx_enable.c > ./mac_rx_enable.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_misc.c > ./mac_misc.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_api.c > ./mac_api.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_disassociate.c > ./mac_disassociate.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_mcps_data.c > ./mac_mcps_data.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_data_req.c > ./mac_data_req.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_process_tal_tx_frame_status.c > ./mac_process_tal_tx_frame_status.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_pib.c > ./mac_pib.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_security.c > ./mac_security.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/mac_scan.c > ./mac_scan.c
gawk -f fileprep.awk $MAC_INSTALL/Applications/Helper_Files/SIO_Support/Inc/sio_handler.h > ./sio_handler.h
gawk -f fileprep.awk $MAC_INSTALL/Include/vendor_nwk_config.h > ./vendor_nwk_config.h
gawk -f fileprep.awk $MAC_INSTALL/Include/return_val.h > ./return_val.h
gawk -f fileprep.awk $MAC_INSTALL/Include/vendor_stack_config.h > ./vendor_stack_config.h
gawk -f fileprep.awk $MAC_INSTALL/Include/mac_build_config.h > ./mac_build_config.h
gawk -f fileprep.awk $MAC_INSTALL/Include/stack_config.h > ./stack_config.h
gawk -f fileprep.awk $MAC_INSTALL/Include/ieee_const.h > ./ieee_const.h
gawk -f fileprep.awk $MAC_INSTALL/Resources/Buffer_Management/Inc/bmm.h > ./bmm.h
gawk -f fileprep.awk $MAC_INSTALL/Resources/Queue_Management/Inc/qmm.h > ./qmm.h
gawk -f fileprep.awk $MAC_INSTALL/MAC/Inc/mac.h > ./mac.h
gawk -f fileprep.awk $MAC_INSTALL/MAC/Inc/mac_internal.h > ./mac_internal.h
gawk -f fileprep.awk $MAC_INSTALL/MAC/Inc/mac_data_structures.h > ./mac_data_structures.h
gawk -f fileprep.awk $MAC_INSTALL/MAC/Inc/mac_api.h > ./mac_api.h
gawk -f fileprep.awk $MAC_INSTALL/MAC/Inc/mac_msg_types.h > ./mac_msg_types.h
gawk -f fileprep.awk $MAC_INSTALL/MAC/Inc/mac_msg_const.h > ./mac_msg_const.h
gawk -f fileprep.awk $MAC_INSTALL/MAC/Inc/mac_config.h > ./mac_config.h
gawk -f fileprep.awk $MAC_INSTALL/TAL/Inc/tal.h > ./tal.h
gawk -f fileprep.awk $MAC_INSTALL/TAL/Inc/tal_types.h > ./tal_types.h
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Inc/tal_slotted_csma.h > ./tal_slotted_csma.h
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Inc/tal_pib.h > ./tal_pib.h
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Inc/atmega128rfa1.h > ./atmega128rfa1.h
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Inc/tal_irq_handler.h > ./tal_irq_handler.h
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Inc/tal_config.h > ./tal_config.h
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Inc/tal_tx.h > ./tal_tx.h
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Inc/tal_constants.h > ./tal_constants.h
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Inc/tal_internal.h > ./tal_internal.h
gawk -f fileprep.awk $MAC_INSTALL/TAL/ATMEGARF_TAL_1/Inc/tal_rx.h > ./tal_rx.h
gawk -f fileprep.awk $MAC_INSTALL/TFA/Inc/tfa.h > ./tfa.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/Inc/armtypes.h > ./armtypes.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/Inc/avrtypes.h > ./avrtypes.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/Inc/avr32types.h > ./avr32types.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/Inc/mcu_types.h > ./mcu_types.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/Inc/pal.h > ./pal.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/Inc/pal_types.h > ./pal_types.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/Generic/Inc/pal_flash.h > ./pal_flash.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/Generic/Inc/pal_uart.h > ./pal_uart.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/Generic/Inc/pal_internal.h > ./pal_internal.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/Generic/Inc/pal_timer.h > ./pal_timer.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/ATMEGA128RFA1/Boards/pal_boardtypes.h > ./pal_boardtypes.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/ATMEGA128RFA1/Inc/pal_usb.h > ./pal_usb.h
gawk -f fileprep.awk $MAC_INSTALL/PAL/MEGA_RF/ATMEGA128RFA1/Inc/pal_mcu_generic.h > ./pal_mcu_generic.h
gawk -f fileprep.awk $MAC_INSTALL/Applications/MAC_Examples/$APP/Inc/app_config.h > ./app_config.h
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/usr_mcps_purge_conf.c > examples/Star_Nobeacon/usr_mcps_purge_conf.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/usr_mlme_beacon_notify_ind.c > examples/Star_Nobeacon/usr_mlme_beacon_notify_ind.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/usr_mlme_disassociate_conf.c > examples/Star_Nobeacon/usr_mlme_disassociate_conf.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/usr_mlme_disassociate_ind.c > examples/Star_Nobeacon/usr_mlme_disassociate_ind.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/usr_mlme_get_conf.c > examples/Star_Nobeacon/usr_mlme_get_conf.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/usr_mlme_orphan_ind.c > examples/Star_Nobeacon/usr_mlme_orphan_ind.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/usr_mlme_poll_conf.c > examples/Star_Nobeacon/usr_mlme_poll_conf.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/usr_mlme_rx_enable_conf.c > examples/Star_Nobeacon/usr_mlme_rx_enable_conf.c
gawk -f fileprep.awk $MAC_INSTALL/MAC/Src/usr_mlme_sync_loss_ind.c > examples/Star_Nobeacon/usr_mlme_sync_loss_ind.c
gawk -f fileprep.awk $MAC_INSTALL/Applications/MAC_Examples/$APP/Inc/app_config.h > examples/Star_Nobeacon/app_config.h
gawk -f fileprep.awk $MAC_INSTALL/Applications/MAC_Examples/$APP/Src/main.c > examples/Star_Nobeacon/example_main.c
